/**
 * Built-in word bank for each game category.
 * Each category should have ≥ 30 words for meaningful randomness.
 */
import { Category } from '../types/game.types';

export const CATEGORY_LABELS: Record<Category, string> = {
  [Category.PLACES]: 'Places',
  [Category.SPORTS]: 'Sports',
  [Category.OBJECTS]: 'Objects',
  [Category.FOOD]: 'Food',
  [Category.MOVIES]: 'Movies',
  [Category.ANIMALS]: 'Animals',
};

export const WORD_BANK: Record<Category, string[]> = {
  [Category.PLACES]: [
    'Eiffel Tower',
    'Great Wall of China',
    'Sahara Desert',
    'Amazon Rainforest',
    'Niagara Falls',
    'Grand Canyon',
    'Machu Picchu',
    'Mount Everest',
    'Colosseum',
    'Taj Mahal',
    'Statue of Liberty',
    'Pyramids of Giza',
    'Big Ben',
    'Sydney Opera House',
    'Stonehenge',
    'Venice Canals',
    'Santorini',
    'Maldives',
    'Antarctica',
    'Times Square',
    'Hollywood',
    'Tokyo Tower',
    'Burj Khalifa',
    'Golden Gate Bridge',
    'Angkor Wat',
    'Petra',
    'Yellowstone',
    'Bermuda Triangle',
    'Chernobyl',
    'Vatican City',
    'Area 51',
    'North Pole',
  ],

  [Category.SPORTS]: [
    'Basketball',
    'Cricket',
    'Tennis',
    'Swimming',
    'Fencing',
    'Archery',
    'Boxing',
    'Gymnastics',
    'Surfing',
    'Skateboarding',
    'Ice Hockey',
    'Rugby',
    'Baseball',
    'Golf',
    'Volleyball',
    'Badminton',
    'Table Tennis',
    'Wrestling',
    'Karate',
    'Judo',
    'Cycling',
    'Horse Racing',
    'Formula 1',
    'Rock Climbing',
    'Snowboarding',
    'Water Polo',
    'Polo',
    'Lacrosse',
    'Rowing',
    'Weightlifting',
    'Triathlon',
    'Handball',
  ],

  [Category.OBJECTS]: [
    'Telescope',
    'Umbrella',
    'Hourglass',
    'Compass',
    'Lantern',
    'Typewriter',
    'Gramophone',
    'Microscope',
    'Chandelier',
    'Boomerang',
    'Kaleidoscope',
    'Metronome',
    'Abacus',
    'Sundial',
    'Periscope',
    'Sextant',
    'Globe',
    'Anvil',
    'Bellows',
    'Monocle',
    'Slingshot',
    'Trident',
    'Locket',
    'Treasure Chest',
    'Spinning Wheel',
    'Crystal Ball',
    'Magic Carpet',
    'Swiss Army Knife',
    'Rubik\'s Cube',
    'Snow Globe',
    'Dream Catcher',
    'Wind Chime',
  ],

  [Category.FOOD]: [
    'Sushi',
    'Croissant',
    'Tacos',
    'Ramen',
    'Pizza',
    'Paella',
    'Dim Sum',
    'Gelato',
    'Baklava',
    'Churros',
    'Pho',
    'Kebab',
    'Falafel',
    'Tiramisu',
    'Nachos',
    'Biryani',
    'Pad Thai',
    'Mochi',
    'Waffles',
    'Goulash',
    'Ceviche',
    'Samosa',
    'Empanada',
    'Baguette',
    'Fondue',
    'Pretzel',
    'Dumplings',
    'Bruschetta',
    'Macarons',
    'Crepe',
    'Cannoli',
    'Spring Rolls',
  ],

  [Category.MOVIES]: [
    'Inception',
    'Titanic',
    'Interstellar',
    'The Godfather',
    'Jurassic Park',
    'Avatar',
    'The Matrix',
    'Gladiator',
    'Forrest Gump',
    'The Lion King',
    'Star Wars',
    'Harry Potter',
    'Lord of the Rings',
    'Batman',
    'Spider-Man',
    'Jaws',
    'Rocky',
    'Toy Story',
    'Finding Nemo',
    'Frozen',
    'Shrek',
    'Pirates of the Caribbean',
    'The Avengers',
    'Black Panther',
    'Transformers',
    'Indiana Jones',
    'Mission Impossible',
    'James Bond',
    'The Terminator',
    'E.T.',
    'Back to the Future',
    'Ghostbusters',
  ],

  [Category.ANIMALS]: [
    'Chameleon',
    'Pangolin',
    'Axolotl',
    'Narwhal',
    'Platypus',
    'Flamingo',
    'Porcupine',
    'Armadillo',
    'Octopus',
    'Jellyfish',
    'Seahorse',
    'Peacock',
    'Penguin',
    'Koala',
    'Red Panda',
    'Snow Leopard',
    'Cheetah',
    'Komodo Dragon',
    'Wolverine',
    'Toucan',
    'Parrot',
    'Dolphin',
    'Manta Ray',
    'Sloth',
    'Capybara',
    'Hedgehog',
    'Chinchilla',
    'Otter',
    'Lynx',
    'Bison',
    'Falcon',
    'Iguana',
  ],
};
