/**
 * Built-in word bank for each game category.
 * Each category should have ≥ 30 words for meaningful randomness.
 */
import { Category } from '../types/game.types';

export const CATEGORY_LABELS: Record<Category, string> = {
  [Category.PLACES]: 'Places',
  [Category.SPORTS]: 'Sports',
  [Category.OBJECTS]: 'Objects',
  [Category.FOOD]: 'Food',
  [Category.MOVIES]: 'Movies',
  [Category.ANIMALS]: 'Animals',
};

export const WORD_BANK: Record<Category, string[]> = {
  [Category.PLACES]: [
    'Taj Mahal',
    'Goa Beach',
    'Burj Khalifa',
    'Eiffel Tower',
    'Mount Everest',
    'Lulu Mall',
    'Wonderla Amusement Park',
    'Marina Beach',
    'Tirupati Temple',
    'Kerala Backwaters',
    'Ooty',
    'Munnar',
    'Kashmir',
    'Andaman Islands',
    'Disneyland',
    'Las Vegas',
    'Dubai',
    'Maldives',
    'Vatican City',
    'Times Square',
    'Pyramids of Egypt',
    'Great Wall of China',
    'Hogwarts (Harry Potter)',
    'Jurassic Park',
    'Area 51',
    'Bermuda Triangle',
    'Antarctica',
    'Amazon Rainforest',
    'Grand Canyon',
    'Niagara Falls',
    'Mecca',
    'Statue of Liberty',
    'Ramoji Film City',
    'Gateway of India',
    'Red Fort',
    'Charminar',
    'Kanyakumari',
    'Rameshwaram',
    'Ajanta Ellora Caves',
    'Sydney Opera House',
    'Bangkok',
    'Singapore',
    'London',
    'Paris',
    'New York',
    'Police Station',
    'Hospital',
    'School',
    'Haunted House',
    'Graveyard / Cemetery',
    'Cinema Theatre',
    'Bank',
    'Supermarket / Grocery Store',
    'Airport',
    'Railway Station',
    'Bus Stand',
    'Restaurant',
    'Gym',
    'Museum',
    'Hotel',
    'Casino',
    'Zoo',
    'Submarine',
    'Circus',
    'Pirate Ship',
    'Fire Station',
    'Prison',
    'Concert Hall',
    'Factory',
    'Farm',
    'Courtroom',
    'Stadium',
    'Beauty Parlour / Salon',
    'Post Office',
    'Swimming Pool',
    'Space Station',
    'Dental Clinic',
    'Marriage Hall',
    'Shopping Mall',
    'Temple',
    'Church',
    'Mosque',
    'Bakery',
    'Orphanage',
    'Old Age Home',
    'Desert',
    'Treehouse',
    'Lighthouse',
    'Mysore Palace',
    'Qutub Minar',
    'Hawa Mahal',
    'Golden Temple',
    'Sabarimala',
    'Guruvayur Temple',
    'Madurai Meenakshi Temple',
    'Public Toilet',
    'Dentist\'s Clinic',
    'Ammavan\'s House (Grandparent\'s House)',
    'Boys Hostel',
    'Girls Hostel',
    'Principal\'s Office',
    'Driving Test Track',
    'Panchayat Office',
    'Theatre Balcony',
    'Fish Market',
    'Barber Shop',
    'Vegetable Market',
    'Thattukada (Street Food Cart)',
    'Toddy Shop (Kallu Shaap)',
    'Job Interview Room',
    'Exam Hall',
    'Mental Asylum',
    'Treadmill',
    'Bevco / Liquor Store (Kuppi Kada)',
    'Ladies Compartment (Train)',
    'Men\'s Washroom',
    'Ammayi\'s (Aunt\'s) Gossip Corner',
    'Auto Rickshaw Stand',
    'Ration Shop',
    'De-addiction Centre',
    'Massage Parlour / Spa',
    'Oyo Room',
    'Traffic Jam',
    'Gulf / Dubai Labour Camp',
    'Hair Transplant Clinic'
  ],

  [Category.SPORTS]: [
    'Cricket',
    'Football',
    'Badminton',
    'Kabaddi',
    'WWE / Pro Wrestling',
    'Chess',
    'Carrom',
    'Hide and Seek',
    'Tug of War',
    'Kho Kho',
    'Gully Cricket',
    'Tennis',
    'Swimming',
    'Boxing',
    'Formula 1 Racing',
    'Hockey',
    'Volleyball',
    'Basketball',
    'Table Tennis',
    'Golf',
    'Archery',
    'Surfing',
    'Karate',
    'Judo',
    'Gymnastics',
    'Horse Racing',
    'Cycling',
    'Skateboarding',
    'Marathon',
    'Weightlifting',
    'Snooker / Billiards',
    'Rugby',
    'Water Polo',
    'Arm Wrestling',
    'Darts',
    'Bowling',
    'Ice Skating',
    'Ludo',
    'Snake and Ladder',
    'Musical Chairs',
    'Throwball',
    'High Jump',
    'Long Jump',
    'Javelin Throw',
    'Shot Put',
    'Relay Race',
    'Seven Stones (Lagori)',
    'Kite Flying',
    'Kalaripayattu',
    'Wrestling / Kushti',
    'Bull Taming (Jallikattu)',
    'Boat Race (Vallam Kali)',
    'Dodgeball',
    'Frisbee',
    'Paintball',
    'Parkour',
    'Rock Climbing',
    'Scuba Diving',
    'Skiing',
    'Snowboarding',
    'Trekking',
    'Bungee Jumping',
    'Skydiving',
    'Sumo Wrestling',
    'Taekwondo',
    'Fencing',
    'Kickboxing',
    'Kung Fu',
    'Polo',
    'Handball',
    'Squash',
    'Cards (Rummy)',
    'Uno',
    'Monopoly',
    'Scrabble',
    'Video Games / Esports',
    'Thumb Wrestling',
    'Pillow Fight',
    'Chor Police (Cops & Robbers)',
    'Blind Man\'s Buff (Kannam Pothi)',
    'Ice and Water',
    'Statue (Lock & Key)',
    'Book Cricket',
    'Pen Fight',
    'Lemon and Spoon Race',
    'Sack Race',
    'Super Mario',
    'PUBG / BGMI',
    'Free Fire',
    'Angry Birds',
    'Candy Crush',
    'Temple Run',
    'Subway Surfers',
    'Wife Carrying',
    'WWE Royal Rumble',
    'Musical Chairs (with angry aunties)',
    'Running behind KSRTC Bus',
    'Bargaining with Auto Driver',
    'Dog Chasing (Nayinte Oottam)',
    'Slapping Match',
    'Staring Contest',
    'Eating Competition',
    'Dodge the Flying Chappal',
    'Catching the Chicken'
  ],

  [Category.OBJECTS]: [
    'Smartphone',
    'Television',
    'Laptop',
    'Refrigerator',
    'Washing Machine',
    'Mirror',
    'Knife',
    'Umbrella',
    'Helmet',
    'Toothbrush',
    'Towel',
    'Pillow',
    'Blanket',
    'Wall Clock',
    'Spectacles / Glasses',
    'Shoes',
    'Bicycle',
    'Motorcycle',
    'Car',
    'Pressure Cooker',
    'Mixer Grinder',
    'Iron Box',
    'Ceiling Fan',
    'Air Conditioner',
    'Sofa',
    'Dining Table',
    'Broomstick',
    'Mop',
    'Toilet Paper',
    'Soap',
    'Shampoo',
    'Comb',
    'Scissors',
    'Nail Clipper',
    'Water Bottle',
    'Backpack',
    'Wallet',
    'Keys',
    'Pen',
    'Diary',
    'Matchbox',
    'Candle',
    'Perfume',
    'Lipstick',
    'Guitar',
    'Flute',
    'Camera',
    'Headphones',
    'Smartwatch',
    'Dumbbell',
    'Gold Ring',
    'Diamond Necklace',
    'Hairbrush',
    'Nail Polish',
    'Eyeliner',
    'Earrings',
    'Bangles',
    'Watch',
    'Belt',
    'Tie',
    'Socks',
    'Slippers / Chappals',
    'Trousers',
    'Shirt',
    'T-shirt',
    'Saree',
    'Dhoti / Mundu',
    'Handkerchief',
    'Raincoat',
    'Handbag / Purse',
    'Suitcase',
    'Lunchbox',
    'Thermos Flask',
    'Mug',
    'Glass',
    'Plate',
    'Spoon',
    'Fork',
    'Frying Pan',
    'Gas Stove',
    'Remote Control',
    'Mouse',
    'Keyboard',
    'Pendrive',
    'Power Bank',
    'Charger',
    'Speaker',
    'Microphone',
    'Tripod',
    'Drone',
    'Calculator',
    'Book',
    'Notebook',
    'Pencil',
    'Eraser',
    'Stapler',
    'Glue',
    'Calendar',
    'Photo Frame',
    'Dustbin',
    'Bucket',
    'Toothpaste',
    'Mattress',
    'Bed',
    'Mosquito Net',
    'Toilet Brush',
    'Underwear / Jetti',
    'Lungi / Kaili',
    'Diaper',
    'Wig',
    'Fake Teeth (Denture)',
    'Plunger',
    'Earbud',
    'Nose Ring',
    'Back Scratcher',
    'Dustpan',
    'Mousetrap',
    'Mosquito Bat / Racket',
    'Safety Pin',
    'Bindi / Pottu',
    'Stethoscope',
    'Thermometer',
    'Walking Stick',
    'Wheelchair',
    'False Eyelashes',
    'Hairpin',
    'Flying Chappal / Slipper',
    'Burner Phone / Pocophone',
    'Bathing Mug with a Hole',
    'Leaking Tap',
    'Ring Guard / Itch Guard',
    'Vicks Inhaler',
    'Ear Wax Picker (Thotti)',
    'Dulcolax / Laxative',
    'Pregnancy Test Kit',
    'Lubricant',
    'Adult Diaper',
    'Kerala Towel (Thorthu)',
    'Spittoon (Kolambi)',
    'Auntie\'s Nighty',
    'Fake Mustache',
    'Straitjacket'
  ],

  [Category.FOOD]: [
    'Biryani',
    'Masala Dosa',
    'Idli Sambar',
    'Vada Pav',
    'Samosa',
    'Pani Puri',
    'Chole Bhature',
    'Butter Chicken',
    'Naan',
    'Paneer Butter Masala',
    'Pizza',
    'Burger',
    'French Fries',
    'Ice Cream',
    'Chocolate',
    'Cake',
    'Gulab Jamun',
    'Jalebi',
    'Rasgulla',
    'Maggi Noodles',
    'Momos',
    'Chai / Tea',
    'Coffee',
    'Lassi',
    'Buttermilk',
    'Shawarma',
    'Fried Rice',
    'Chilli Chicken',
    'Ghee Roast',
    'Appam',
    'Puttu',
    'Parotta',
    'Beef Roast',
    'Kappa (Tapioca)',
    'Fish Fry',
    'Prawn Masala',
    'Kebab',
    'Tandoori Chicken',
    'Croissant',
    'Sushi',
    'Pasta',
    'Sandwich',
    'Salad',
    'Omelette',
    'Pancake',
    'Waffle',
    'Donut',
    'Popcorn',
    'Chips',
    'Sadya',
    'Pav Bhaji',
    'Bhel Puri',
    'Sev Puri',
    'Kachori',
    'Rasmalai',
    'Kheer / Payasam',
    'Halwa',
    'Laddoo',
    'Barfi',
    'Kaju Katli',
    'Mysore Pak',
    'Pedha',
    'Soan Papdi',
    'Falooda',
    'Kulfi',
    'Pastry',
    'Biscuit',
    'Aloo Paratha',
    'Rajma Chawal',
    'Dal Makhani',
    'Palak Paneer',
    'Chicken Tikka',
    'Mutton Curry',
    'Crab Roast',
    'Medu Vada',
    'Upma',
    'Poha',
    'Dhokla',
    'Spring Roll',
    'Chowmein / Noodles',
    'Manchurian',
    'Garlic Bread',
    'Soup',
    'Boiled Egg',
    'Bhurji',
    'Milk',
    'Sharbat',
    'Nimbu Pani (Lemonade)',
    'Coconut Water',
    'Sugarcane Juice',
    'Mango Shake',
    'Banana',
    'Apple',
    'Mango',
    'Grapes',
    'Watermelon',
    'Papaya',
    'Pineapple',
    'Orange',
    'Strawberry',
    'Cherry',
    'Jackfruit',
    'Guava',
    'Pomegranate',
    'Thalassery Biryani',
    'Kuzhimanthi',
    'Alfam',
    'Karimeen Pollichathu',
    'Bitter Gourd / Pavakka',
    'Sardine / Mathi Fry',
    'Bullseye / Half Boil',
    'Raw Mango with Salt & Chilli',
    'Cotton Candy / Panji Mittai',
    'Kappi (Black Coffee)',
    'Pazham Pori (Banana Fritters)',
    'Uzhunnu Vada',
    'Mutta Baji (Egg Bajji)',
    'Bonda',
    'Sip-Up / Ice Pepsi',
    'Kadalakkari',
    'Beef Ularthiyathu',
    'Porotta Curry',
    'Jackfruit / Chakka',
    'Toddy / Kallu',
    'Rum / Old Monk',
    'Beer',
    'Maggie with Egg',
    'Hostel Food',
    'Chyawanprash',
    'Pulse Candy',
    'Hajmola',
    'Kissan Jam',
    'Prasadam / Panchamritham',
    'Leftover Rice / Pazhamkanji',
    'Sada Dosa (Paper Roast)',
    'Free Kalyanam (Wedding) Food',
    'Train Pantry Biryani',
    'Burnt Toast',
    'Black Halwa (Bouncing Halwa)',
    'Magic Mushroom',
    'Bhaang / Bhila',
    'Raw Onion',
    'Kallu and Kappa (Toddy & Tapioca)'
  ],

  [Category.MOVIES]: [
    // Malayalam
    'Manichitrathazhu',
    'Drishyam',
    'Premam',
    'Kumbalangi Nights',
    'Bangalore Days',
    'Kireedam',
    'Spadikam',
    'Punjabi House',
    'Kalyanaraman',
    'CID Moosa',
    'Chithram',
    'Kilukkam',
    'Sandhesam',
    'Narasimham',
    'Rajamanikyam',
    'Nadodikattu',
    'Ramji Rao Speaking',
    'In Harihar Nagar',
    'Aavesham',
    'Manjummel Boys',
    'Aadu',
    'Lucifer',
    'Bheeshma Parvam',
    'Oru Vadakkan Veeragatha',
    'Godfather',
    'My Dear Kuttichathan',
    'Kunjiramayanam',
    'Vellimoonga',
    'Mayavi',
    'Chotta Mumbai',
    'Pokkiri Raja',
    'Ustad Hotel',
    'Ohm Shanthi Oshaana',
    'Thattathin Marayathu',
    'Maheshinte Prathikaaram',
    'Action Hero Biju',
    'Sudani from Nigeria',
    'Romancham',
    'Hridayam',
    'Minnal Murali',
    'Trance',
    'Bramayugam',
    'Pulimurugan',
    'Arappatta Kettiya Gramathil',
    'Thoovanathumbikal',
    'Namukku Parkkan Munthirithoppukal',
    'Njangal Santhushtaranu',
    'Meesa Madhavan',
    'Pattanapravesham',
    'Yodha',
    'Vandanam',
    'Lelam',
    'Thenmavin Kombath',
    'Bhargavi Nilayam',

    // Tamil
    'Baahubali',
    'Vikram',
    'Kaithi',
    'Enthiran (Robot)',
    'Sivaji',
    'Padayappa',
    'Ghilli',
    'Mankatha',
    'Thuppakki',
    'Anniyan',
    'Nayagan',
    'KGF',
    'Kantara',
    'Leo',
    'Jailer',
    'Basha',
    'Indian',
    'Asuran',
    'Vada Chennai',
    '96',
    'Pokkiri',
    'Billa',
    'Master',
    'Petta',
    'Theri',
    'Mersal',
    'Bigil',
    'Kanchana',
    'Muni',
    'Chandramukhi',
    'Jeans',
    'Boys',
    'Roja',
    'Bombay',
    'Arunachalam',
    'Singam',
    'Saamy',
    'Ratsasan',
    'Karnan',
    'Gargi',
    'Maharaja',

    // Hindi
    'Sholay',
    'Dilwale Dulhania Le Jayenge (DDLJ)',
    '3 Idiots',
    'Dangal',
    'Lagaan',
    'Zindagi Na Milegi Dobara',
    'Yeh Jawaani Hai Deewani',
    'Kuch Kuch Hota Hai',
    'Kabhi Khushi Kabhie Gham',
    'Munna Bhai M.B.B.S.',
    'Gangs of Wasseypur',
    'PK',
    'Bajrangi Bhaijaan',
    'Chennai Express',
    'Hera Pheri',
    'Jawan',
    'Pathaan',
    'Animal',
    'Pushpa',
    'Kal Ho Naa Ho',
    'Swades',
    'Rang De Basanti',
    'Sultan',
    'Dil Chahta Hai',
    'Phir Hera Pheri',
    'Welcome',
    'Dhamaal',
    'Bhool Bhulaiyaa',
    'Golmaal',
    'Lage Raho Munna Bhai',
    'Jab We Met',
    'Chak De India',
    'Krrish',
    'Koi Mil Gaya',
    'Andhadhun',
    'Drishyam (Hindi)',
    'Queen',
    'Uri',
    'Stree',
    'Thenkasipattanam',
    'Thommanum Makkalum',
    'Chathikkatha Chanthu',
    'Pulival Kalyanam',
    'Three Kings',
    'Happy Husbands',
    'Amar Akbar Anthony',
    'Adi Kapyare Kootamani',
    'CID Unnikrishnan B.A., B.Ed.',
    'Kottayam Kunjachan',
    'Hitler',
    'Godha',
    'Neram',
    'Oru Vadakkan Selfie',
    'Njan Prakashan',
    'Boss Engira Bhaskaran',
    'Oru Kal Oru Kannadi',
    'Varuthapadatha Valibar Sangam',
    'Chennai 600028',
    'Panchathanthiram',
    'Avvai Shanmugi',
    'Vasool Raja MBBS',
    'Soodhu Kavvum',
    'Ayan',
    'VIP (Velaiilla Pattadhari)',
    'Maari',
    'Golmaal 3',
    'Chup Chup Ke',
    'Hungama',
    'Garam Masala',
    'Andaz Apna Apna',
    'Om Shanti Om',
    'Taare Zameen Par',
    'Azhakiya Ravanan',
    'Mookilla Rajyathu',
    'Kinnaripuzhayoram',
    'Malayali Mamanu Vanakkam',
    'Chattambinadu',
    'Hallo',
    'Vellanakalude Nadu',
    'Thamizh Padam',
    'Thamizh Padam 2',
    'Kalakalappu',
    'Aambala',
    'Idharkuthane Aasaipattai Balakumara',
    'Comali',
    'Doctor',
    'Tees Maar Khan',
    'Deshdrohi',
    'Gunda',
    'Jaani Dushman',
    'Golmaal: Fun Unlimited',
    'Grand Masti',
    'Delhi Belly'
  ],

  [Category.ANIMALS]: [
    'Dog',
    'Cat',
    'Cow',
    'Elephant',
    'Tiger',
    'Lion',
    'Monkey',
    'Snake',
    'Crocodile',
    'Mosquito',
    'Housefly',
    'Cockroach',
    'Spider',
    'Ant',
    'Rat',
    'Rabbit',
    'Horse',
    'Donkey',
    'Goat',
    'Pig',
    'Camel',
    'Bear',
    'Kangaroo',
    'Panda',
    'Penguin',
    'Dolphin',
    'Whale',
    'Shark',
    'Frog',
    'Turtle',
    'Dinosaur',
    'Dragon',
    'Unicorn',
    'Peacock',
    'Eagle',
    'Crow',
    'Pigeon',
    'Parrot',
    'Owl',
    'Ostrich',
    'Zebra',
    'Giraffe',
    'Hippopotamus',
    'Rhinoceros',
    'Cheetah',
    'Leopard',
    'Wolf',
    'Fox',
    'Bat',
    'Squirrel',
    'Chameleon',
    'Octopus',
    'Panther',
    'Jaguar',
    'Puma',
    'Hyena',
    'Jackal',
    'Polar Bear',
    'Koala',
    'Alligator',
    'Tortoise',
    'Python',
    'Anaconda',
    'Cobra',
    'Lizard',
    'Toad',
    'Gorilla',
    'Chimpanzee',
    'Orangutan',
    'Baboon',
    'Sparrow',
    'Woodpecker',
    'Chicken / Hen',
    'Rooster',
    'Duck',
    'Swan',
    'Goose',
    'Emu',
    'Flamingo',
    'Mouse',
    'Hamster',
    'Guinea Pig',
    'Mole',
    'Porcupine',
    'Hedgehog',
    'Mule',
    'Deer',
    'Antelope',
    'Gazelle',
    'Moose',
    'Elk',
    'Reindeer',
    'Bull',
    'Buffalo / Bison',
    'Sheep',
    'Boar',
    'Squid',
    'Jellyfish',
    'Starfish',
    'Seahorse',
    'Crab',
    'Lobster',
    'Oyster',
    'Snail',
    'Butterfly',
    'Moth',
    'Bee',
    'Wasp',
    'Scorpion',
    'Centipede',
    'Earthworm',
    'Leech',
    'Bedbug / Moota',
    'Lice / Pen',
    'Dung Beetle',
    'Tapeworm',
    'Komodo Dragon',
    'Pug (Vodafone Dog)',
    'Golden Retriever',
    'Street Dog / Nadan Patti',
    'Black Cat',
    'Termite / Chirathal',
    'Bandicoot / Peruchaazhi',
    'Desi Cow / Nadan Pasu',
    'Dog with 3 legs',
    'Angry Buffalo / Pothu',
    'Honey Badger',
    'Skunk',
    'Bloodsucker Lizard / Ondu',
    'Drunk Monkey',
    'Giant Mosquito / Gothuku',
    'Toad / Pori Thavala',
    'Snail / Natha',
    'Paambu (Snake / Drunkard)',
    'Cockroach (Flying Mode)',
    'Mating Cats (Karayunna Poocha)',
    'Pesticide Immune Mosquito'
  ],
};
